### ISSUE TITLE
Testing model

### ISSUE THREAD

**Issue by Shringa13** [EmilianoGagliardiEmanueleGhelfi/CNN-compression-performance#1]
Hello,
I am trying to test this model and facing issue while running workflow.py. it giving me error:
    user_module = importlib.import_module(args.module_name[0])
TypeError: 'NoneType' object is not subscriptable

Can you please tell me what is missing? 
Also, for mnist_models file 2conv_2fc.py is having below variables:
  checkpoint_prefix = 'CNNs/mnist_models/net_serializations/2conv_2fc/net'
  checkpoint_path = 'CNNs/mnist_models/net_serializations/2conv_2fc'
I am not able to get this path.

**Comment by emilianogagliardi** [comment]
How do you call the script? Have you defined a class that implements ToBeQuantizedNetwork defined in pattern/pattern.py?

**Comment by Shringa13** [comment]
Sorry. How do we do that?
Can you give me an example of it?

**Comment by emilianogagliardi** [comment]
You can find an example of the script invocation command in aut.sh, or better, you can see the meaning of the parameters with 
`python workflow.py --help`
To define an implementation of ToBeQuantizedNetwork you can take as example CNN-compression-performance/tf_quantize/CNNs/mnist_models/2conv_2fc.py. I suggest you to watch the definition of ToBeQuantizedNetwork in CNN-compression-performance/tf_quantize/pattern/pattern.py.
I'm sorry, I know this is not user friendly, but we used this implementation mechanism to be fast in evaluating different networks. The first objective was to obtain performance parameters to compare different nets.

**Comment by Shringa13** [comment]
Thank you . I will read it again and will try to run it and if I still face any issue will let you know

**Comment by Shringa13** [comment]
1 more question: Where I can find these checkpoints
checkpoint_prefix = 'CNNs/mnist_models/net_serializations/2conv_2fc/net'
checkpoint_path = 'CNNs/mnist_models/net_serializations/2conv_2fc'

**Comment by emilianogagliardi** [comment]
No problem, I hope we will be able to provide a better documentation one of this days. 
Actually you should create the net_serialization dir, then the script will save into it the network with its weights after the training (if you used --train=True) and the quantized network (still, if you used --quantize=True). To quantise the net you have to install the TensorFlow tool, and export the env variable  TF_HOME containing the path to you TensorFlow home.

**Comment by Shringa13** [comment]
You guys have already provided so much information and thank you for sharing this details. I have just started learning this and faced issue while implementing quantization part. I can able to run your code now :+1: 
If you can able to look into my code and let me know where I am going wrong, here is the link of all the details:
https://stackoverflow.com/questions/47492130/you-must-feed-a-value-for-placeholder-tensor-placeholder-with-dtype-float-and?noredirect=1#comment82006554_47492130

**Comment by emilianogagliardi** [comment]
I will try

**Comment by Shringa13** [comment]
Hey,
I am still getting error for this 2 variables:
checkpoint_prefix = 'CNNs/mnist_models/net_serializations/2conv_2fc/net'
checkpoint_path = 'CNNs/mnist_models/net_serializations/2conv_2fc'

I have created 3 directories as shown in path above net_serializations -> 2conv_2fc -> net and getting error ::
ValueError: Parent directory of CNNs/net_serializations/2conv_2fc/net  doesn't exist, can't save.
Is there anything else I am missing? 
I am running your code by providing below command:
 python workflow.py --quantize True --evaluate True --train True --module_name 
 CNNs.mnist_models.2conv_2fc --class_name Mnist2Conv2Fc

and have the same folder structure as you have mentioned.
