### ISSUE TITLE
How to save the model after quantized?

### ISSUE THREAD

**Issue by RichardMrLu** [EmilianoGagliardiEmanueleGhelfi/CNN-compression-performance#3]
I implement linear quantization by PyTorch,but after quantized, model's size unchanged,it still save in float format, how to save the quantized model? Thanks for your help.

**Comment by EmanueleGhelfi** [comment]
Hi,
What framework are using for quantisation? Caffe Ristretto or Tensorflow?

**Comment by RichardMrLu** [comment]
I use PyTorch, I google this problem then find a PPT, I see you had solve this issue, so I input this question here...
I didn't use TF, while PyTorch save model as a dict format.

**Comment by EmanueleGhelfi** [comment]
We've studied the compression method of Caffe Ristretto and Tensorflow. We discovered that Caffe does not save the compressed model but saves the quantised values as float, then it performs the computation with low precision values. Tensorflow saves the weights with low precision (and in this way the size of the model it's actually reduced). We've not studied the compression algorithm used by PyTorch, if the model size is unchanged probably it can be an algorithm like the one used by Caffe Ristretto. You have to check the actual implementation of net quantisation used in PyTorch.

**Comment by RichardMrLu** [comment]
How do you save the quantized model in Tensorflow? I try to change this method in PyTorch. I am really appreciate your help.

**Comment by EmanueleGhelfi** [comment]
Actually we call the quantise method of Tensorflow, it should be this one: 
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/quantization/quantize_graph.py]

**Comment by RichardMrLu** [comment]
Thanks for your help, I will try to do it.
